services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    networks:
      - postgres_network

  # pgAdmin service (visualizer)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.com  # Login email
      PGADMIN_DEFAULT_PASSWORD: pass  # Login password
    ports:
      - "5050:80"  # Expose the pgAdmin web interface
    networks:
      - postgres_network
    volumes:
      - ./postgresconfig.json:/pgadmin4/servers.json  # Pre-configured servers
    depends_on:
      - postgres  # Ensure PostgreSQL starts before pgAdmin

  rabbitmq:
    image: rabbitmq:4-management
    container_name: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  postgres_network:
    driver: bridge