services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    networks:
      - ankiai_network

  # pgAdmin service (visualizer)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.com  # Login email
      PGADMIN_DEFAULT_PASSWORD: pass  # Login password
    ports:
      - "5050:80"  # Expose the pgAdmin web interface
    networks:
      - ankiai_network
    volumes:
      - ./postgresconfig.json:/pgadmin4/servers.json  # Pre-configured servers
    depends_on:
      - postgres  # Ensure PostgreSQL starts before pgAdmin

  rabbitmq:
    image: rabbitmq:4-management
    container_name: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - ankiai_network

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318
    networks:
      - ankiai_network
  
  local.consumer:
    image: eda-consumer
    container_name: "local.eda-consumer"
    ports:
      - "5271:8080"
    # For learning purposes: In ASP.NET, if you run using dll, the default
    # ASPNETCORE_ENVIRONMNENT is Production! Commented out below just to reiterate
    # the point
    # environment:
    #  - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - ankiai_network
    depends_on:
      - rabbitmq

  local.producer:
    image: eda-producer
    container_name: "local.eda-producer"
    ports:
      - "5093:8080"
    # For learning purposes: In ASP.NET, if you run using dll, the default
    # ASPNETCORE_ENVIRONMNENT is Production! Commented out below just to reiterate
    # the point
    # environment:
    #  - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - ankiai_network
    depends_on:
      - rabbitmq

networks:
  ankiai_network:
    driver: bridge